<?xml version="1.0" encoding="utf-8"?><Database Name="FaxConfigDB" Class="FaxLinQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database\FaxConfigDB.mdf;Integrated Security=True;User Instance=False" SettingsObjectName="SendFaxApp.Properties.Settings" SettingsPropertyName="FaxConfigDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FaxConfig" Member="FaxConfigs">
    <Type Name="FaxConfig">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HostName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SenderName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="WebSocketUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FileSaveUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>